#!/usr/bin/sh

wmname LG3D
sxhkd &
$HOME/.config/polybar/launch.sh
#xdo above -t $(xdo id -n root) $(xdo id -n polybar)
override-redirect = true
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a scrcpy desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a jetbrains-idea-ce state=floating 
